name: Update File List and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Result/**'
      - '.github/workflows/update-file-list.yml'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List files in Result before generation
        run: |
          echo "📁 Файлы в Result до генерации:"
          ls -la Result/ || echo "Result папка не найдена"

      - name: Generate file list
        run: |
          chmod +x generate-manifest.sh
          if command -v node &> /dev/null; then
            node generate-manifest.js
          else
            bash generate-manifest.sh
          fi
          
          # Проверяем, что manifest.json валидный JSON
          if ! python3 -c "import json; json.load(open('Result/manifest.json'))" 2>/dev/null; then
            if command -v node &> /dev/null; then
              node -e "JSON.parse(require('fs').readFileSync('Result/manifest.json', 'utf8'))" || {
                echo "❌ Ошибка: manifest.json невалидный JSON!"
                exit 1
              }
            fi
          fi

      - name: Verify manifest was generated
        run: |
          if [ ! -f "Result/manifest.json" ]; then
            echo "❌ Ошибка: manifest.json не был создан!"
            exit 1
          fi
          echo "✅ manifest.json существует"
          echo "📋 Содержимое manifest.json:"
          cat Result/manifest.json
          
      - name: List files in Result after generation
        run: |
          echo "📁 Файлы в Result после генерации:"
          ls -la Result/ || echo "Result папка не найдена"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Сначала проверяем, что manifest.json был сгенерирован правильно
          echo "📋 Проверяем содержимое manifest.json перед коммитом:"
          cat Result/manifest.json
          
          # Всегда добавляем manifest.json
          git add Result/manifest.json
          
          # Проверяем текущее состояние
          echo "📊 Статус изменений:"
          git status --short
          
          # Проверяем, есть ли изменения в staged файлах
          if git diff --staged --quiet; then
            echo "⚠️ manifest.json не изменился в staged области"
            # Проверяем, есть ли различия с HEAD
            if git diff HEAD -- Result/manifest.json | grep -q .; then
              echo "✅ Обнаружены различия с HEAD, коммитим"
              git commit -m "🤖 Auto-update: обновлен список файлов в Result (удалены старые файлы)"
            else
              echo "ℹ️ Изменений нет - manifest.json актуален"
              # Но все равно делаем commit для гарантии обновления
              git commit --allow-empty -m "🤖 Auto-update: проверка списка файлов в Result"
            fi
          else
            echo "✅ Обнаружены изменения в manifest.json (staged)"
            # Показываем что именно изменилось
            echo "📝 Изменения:"
            git diff --staged Result/manifest.json || true
            git commit -m "🤖 Auto-update: обновлен список файлов в Result"
          fi
          
          # Всегда пушим изменения
          echo "📤 Отправляем изменения на GitHub..."
          git push
          echo "✅ manifest.json успешно обновлен и отправлен на GitHub"

      - name: Trigger GitHub Pages deployment
        run: |
          echo "✅ GitHub Pages будет автоматически развернут после push изменений"
          echo "Изменения в Result триггерят workflow deploy-pages.yml"

