name: Update File List

on:
  push:
    branches:
      - main
    paths:
      - 'Result/**'
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate file list
        run: |
          chmod +x generate-manifest.sh
          if command -v node &> /dev/null; then
            node generate-manifest.js
          else
            bash generate-manifest.sh
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Result/manifest.json
          git diff --staged --quiet || git commit -m "Update file list manifest" || exit 0
          git push

